[env:rpipicow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
board = rpipicow
framework = arduino
monitor_speed = 115200
lib_deps = knolleary/PubSubClient@^2.8
